---
# Generate VXLAN Documentation Tasks
# Creates documentation for VXLAN overlay configuration

- name: Create VXLAN documentation directory
  file:
    path: "{{ documentation_path }}/vxlan"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Generate VXLAN configuration documentation
  template:
    src: vxlan_config.md.j2
    dest: "{{ documentation_path }}/vxlan/{{ inventory_hostname }}_vxlan_config.md"
    mode: '0644'
  delegate_to: localhost

- name: Generate VNI mapping documentation
  template:
    src: vni_mapping.md.j2
    dest: "{{ documentation_path }}/vxlan/vni_mapping.md"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Generate VXLAN security documentation
  template:
    src: vxlan_security.md.j2
    dest: "{{ documentation_path }}/vxlan/vxlan_security.md"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Generate VXLAN topology diagram data
  template:
    src: vxlan_topology.json.j2
    dest: "{{ documentation_path }}/vxlan/vxlan_topology.json"
    mode: '0644'
  delegate_to: localhost
  run_once: true