---
# Cisco Router Configuration Tasks
# Configures basic router functionality for small office internet gateway

- name: Include router validation tasks
  include_tasks: validate.yml
  
- name: Include basic router configuration
  include_tasks: basic_config.yml
  
- name: Include interface configuration
  include_tasks: interface_config.yml
  
- name: Include routing configuration
  include_tasks: routing_config.yml
  
- name: Include NAT configuration
  include_tasks: nat_config.yml
  
- name: Include firewall configuration
  include_tasks: firewall_config.yml
  
- name: Include DHCP configuration
  include_tasks: dhcp_config.yml
  
- name: Include management configuration
  include_tasks: mgmt_config.yml
  
- name: Save router configuration
  ios_config:
    save_when: modified
    
- name: Verify router configuration
  include_tasks: verify.yml