---
- name: Create EC2 instance
  hosts: localhost

  vars:
    aws_region: us-east-1
    instance_type: t3.micro
    key_name: "my-ansible-key"
    _state: present  # present to create, absent to destroy  
  tasks:
    - name: Get default VPC
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "is-default": "true"
      register: vpc_info

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        cidr: "172.31.0.0/20"
        az: "{{ aws_region }}a"
        region: "{{ aws_region }}"
        map_public: true
      register: subnet_info

    - name: Create internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ aws_region }}"
        state: "{{ _state }}"
      register: igw_info

    - name: Create route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ aws_region }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw_info.gateway_id }}"
        subnets:
          - "{{ subnet_info.subnet.id }}"

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "my-security-group"
        description: "Allow SSH access"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: "0.0.0.0/0"
        state: "{{ _state }}"

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "my-instance"
        instance_type: "{{ instance_type }}"
        image_id: "ami-0fd26c36a83ae0088"
        key_name: "{{ key_name }}"
        security_groups:
          - "my-security-group"
        vpc_subnet_id: "{{ subnet_info.subnet.id }}"
        region: "{{ aws_region }}"
        wait: true
        state: "{{ _state }}"
        tags:
          Name: "my-instance"
      register: instance

    - name: Show result
      ansible.builtin.debug:
        msg: "Done!"