---
# Test variables
- name: Variables Test
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/aws_config.yml
    - vars/development.yml

  tasks:
    - name: Show region
      ansible.builtin.debug:
        msg: "AWS region: {{ aws_region }}"

    - name: Show combined vars
      ansible.builtin.debug:
        msg: "Creating {{ instance_name }} ({{ instance_type }}) in {{ aws_region }}"

    - name: Show tags
      ansible.builtin.debug:
        msg: "Tags: {{ resource_tags }}"

    - name: Show specific tag
      ansible.builtin.debug:
        msg: "Environment: {{ resource_tags.Environment }}"

    - name: Show overrides
      ansible.builtin.debug:
        msg: |
          Name: {{ instance_name }}
          Owner: {{ resource_tags.Owner }}

    - name: Test command line override
      ansible.builtin.debug:
        msg: "Message: {{ custom_message | default('none') }}"
