---
- name: Destroy EC2 instance
  hosts: localhost

  vars:
    aws_region: us-east-1
    instance_type: t3.micro
    key_name: "my-ansible-key"
    _state: absent  # present to create, absent to destroy  
  tasks:
    - name: Get default VPC
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "is-default": "true"
      register: vpc_info

    - name: Delete EC2 instance
      amazon.aws.ec2_instance:
        filters:
          tag:Name: "my-instance"
          instance-state-name: ["running", "stopped", "pending", "stopping"]
        region: "{{ aws_region }}"
        state: absent
        wait: true

    - name: Delete security group
      amazon.aws.ec2_security_group:
        name: "my-security-group"
        region: "{{ aws_region }}"
        state: absent

    - name: Get route table info for deletion
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: route_table_info

    - name: Delete route table
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ item.route_table_id }}"
        region: "{{ aws_region }}"
        lookup: id
        state: absent
      loop: "{{ route_table_info.route_tables | default([]) }}"
      when: 
        - not item.associations[0].main | default(false)
      ignore_errors: true

    - name: Delete subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        cidr: "172.31.0.0/20"
        az: "{{ aws_region }}a"
        region: "{{ aws_region }}"
        state: absent

    - name: Delete internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ aws_region }}"
        state: absent

    - name: Show result
      ansible.builtin.debug:
        msg: "Done!"