---
# Advanced Networking Deployment Playbook
# Phase 3: Modern datacenter fabric with performance optimization

- name: Deploy advanced networking capabilities
  hosts: datacenter_fabric_switches
  gather_facts: yes
  vars_files:
    - ../group_vars/vault.yml
  
  pre_tasks:
    - name: Verify device connectivity
      cisco.ios.ios_command:
        commands:
          - show version
      register: device_info
      failed_when: false

    - name: Display device information
      debug:
        msg: "Device {{ inventory_hostname }} is reachable"
      when: device_info is succeeded

  roles:
    # Core roles (already integrated in Phase 2)
    - role: cisco_router
      when: device_type == 'router'
      
    - role: security_hardening
      when: security_hardening_enabled | default(true)
      
    - role: bgp_configuration
      when: bgp_enabled | default(true)

    # Phase 3: Advanced networking roles
    - role: leaf_spine_architecture
      when: fabric_architecture == 'leaf_spine'
      
    - role: vxlan_overlay
      when: vxlan_enabled | default(true)
      
    - role: micro_segmentation
      when: microsegmentation_enabled | default(true)

    # Phase 3: Performance optimization roles  
    - role: performance_optimization
      when: performance_optimization_enabled | default(true)
      
    - role: qos_traffic_engineering
      when: qos_enabled | default(true)
      
    - role: bandwidth_management
      when: bandwidth_management_enabled | default(true)

  post_tasks:
    - name: Validate advanced networking deployment
      include_tasks: ../tasks/validate_advanced_networking.yml
      when: validate_deployment | default(true)

    - name: Generate deployment summary
      debug:
        msg: |
          Advanced networking deployment completed for {{ inventory_hostname }}
          - Fabric architecture: {{ fabric_architecture }}
          - VXLAN enabled: {{ vxlan_enabled }}
          - Micro-segmentation: {{ microsegmentation_enabled }}
          - Performance optimization: {{ performance_optimization_enabled }}
          - QoS traffic engineering: {{ qos_enabled }}
          - Bandwidth management: {{ bandwidth_management_enabled }}