---
# Production overrides
instance_type: t3.small
instance_name: prod-web

# Lock down SSH
ssh_cidr: "10.0.0.0/8"

# Prod tags
resource_tags:
  Environment: production
  Project: homelab-prod
  Owner: enzo
  Backup: yes