---
# Generate Topology Documentation Tasks
# Creates documentation for the leaf-spine fabric topology

- name: Create documentation directory
  file:
    path: "{{ documentation_path }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Generate fabric topology documentation
  template:
    src: fabric_topology.md.j2
    dest: "{{ documentation_path }}/fabric_topology.md"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Generate device configuration summary
  template:
    src: device_config_summary.md.j2
    dest: "{{ documentation_path }}/{{ inventory_hostname }}_config_summary.md"
    mode: '0644'
  delegate_to: localhost

- name: Generate network diagram data
  template:
    src: network_diagram.json.j2
    dest: "{{ documentation_path }}/network_diagram.json"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Generate inventory documentation
  template:
    src: inventory_documentation.md.j2
    dest: "{{ documentation_path }}/inventory_documentation.md"
    mode: '0644'
  delegate_to: localhost
  run_once: true