---
# Leaf Switch Configuration Tasks
# Configures Cisco leaf switches for data center fabric

- name: Configure leaf switch hostname and domain
  cisco.ios.ios_config:
    lines:
      - hostname {{ inventory_hostname }}
      - ip domain-name {{ datacenter_domain }}
      - ip name-server {{ dns_servers | join(' ') }}
    match: line

- name: Enable advanced switching features on leaf
  cisco.ios.ios_config:
    lines:
      - feature bgp
      - feature ospf
      - feature interface-vlan
      - feature lacp
      - feature vpc
      - feature vn-segment-vlan-based
      - feature nv overlay
    match: line

- name: Configure leaf switch interfaces for fabric connectivity
  cisco.ios.ios_config:
    lines:
      - interface {{ item.interface }}
      - description {{ item.description }}
      - no switchport
      - ip address {{ item.ip_address }} {{ item.subnet_mask }}
      - ip ospf network point-to-point
      - ip ospf area {{ ospf_area }}
      - no shutdown
    parents: interface {{ item.interface }}
    match: line
  loop: "{{ leaf_spine_interfaces }}"
  when: leaf_spine_interfaces is defined

- name: Configure leaf management interface
  cisco.ios.ios_config:
    lines:
      - interface {{ mgmt_interface }}
      - ip address {{ mgmt_ip }} {{ mgmt_subnet_mask }}
      - no shutdown
    parents: interface {{ mgmt_interface }}
    match: line

- name: Configure leaf loopback interfaces
  cisco.ios.ios_config:
    lines:
      - interface {{ item.interface }}
      - description {{ item.description }}
      - ip address {{ item.ip_address }} {{ item.subnet_mask }}
      - ip ospf area {{ ospf_area }}
    parents: interface {{ item.interface }}
    match: line
  loop: "{{ leaf_loopback_interfaces }}"
  when: leaf_loopback_interfaces is defined

- name: Configure leaf access ports for servers
  cisco.ios.ios_config:
    lines:
      - interface {{ item.interface }}
      - description {{ item.description }}
      - switchport mode access
      - switchport access vlan {{ item.vlan }}
      - spanning-tree portfast
      - spanning-tree bpduguard enable
      - no shutdown
    parents: interface {{ item.interface }}
    match: line
  loop: "{{ leaf_access_ports }}"
  when: leaf_access_ports is defined

- name: Configure leaf trunk ports for other switches
  cisco.ios.ios_config:
    lines:
      - interface {{ item.interface }}
      - description {{ item.description }}
      - switchport mode trunk
      - switchport trunk allowed vlan {{ item.allowed_vlans }}
      - spanning-tree portfast trunk
      - no shutdown
    parents: interface {{ item.interface }}
    match: line
  loop: "{{ leaf_trunk_ports }}"
  when: leaf_trunk_ports is defined