---
# Underlay Network Configuration Tasks
# Configures the underlay network for leaf-spine fabric

- name: Configure underlay network routing
  cisco.ios.ios_config:
    lines:
      - ip routing
      - ip multicast-routing
      - ip pim sparse-mode
    match: line

- name: Configure underlay VLAN for point-to-point links
  cisco.ios.ios_config:
    lines:
      - vlan {{ item.vlan_id }}
      - name {{ item.name }}
      - state active
    match: line
  loop: "{{ underlay_vlans }}"
  when: underlay_vlans is defined

- name: Configure underlay SVI interfaces
  cisco.ios.ios_config:
    lines:
      - interface vlan{{ item.vlan_id }}
      - description {{ item.description }}
      - ip address {{ item.ip_address }} {{ item.subnet_mask }}
      - ip ospf area {{ ospf_area }}
      - ip ospf network point-to-point
      - ip ospf hello-interval {{ ospf_hello_interval }}
      - ip ospf dead-interval {{ ospf_dead_interval }}
      - no shutdown
    parents: interface vlan{{ item.vlan_id }}
    match: line
  loop: "{{ underlay_svi_interfaces }}"
  when: underlay_svi_interfaces is defined

- name: Configure underlay routing protocol preferences
  cisco.ios.ios_config:
    lines:
      - ip route 0.0.0.0 0.0.0.0 {{ default_gateway }}
    match: line
  when: default_gateway is defined

- name: Configure underlay multicast settings
  cisco.ios.ios_config:
    lines:
      - ip multicast-routing
      - ip pim sparse-mode
      - ip pim rp-address {{ multicast_rp_address }}
    match: line
  when: multicast_enabled | bool and multicast_rp_address is defined