---
- name: Destroy EC2 instance using variables
  hosts: localhost

  # Load variables from external files
  vars_files:
    - ../vars/aws_config.yml
    - ../vars/development.yml  # This can be changed to production.yml

  vars:
    _state: absent

  tasks:
    - name: Display what will be destroyed
      ansible.builtin.debug:
        msg: |
          Destroying {{ instance_name }} in {{ aws_region }}
          Environment: {{ resource_tags.Environment }}
          Security Group: {{ security_group_name }}

    - name: Get default VPC
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "is-default": "true"
      register: vpc_info

    - name: Delete EC2 instance
      amazon.aws.ec2_instance:
        filters:
          tag:Name: "{{ instance_name }}"
          instance-state-name: ["running", "stopped", "pending", "stopping"]
        region: "{{ aws_region }}"
        state: absent
        wait: true

    - name: Wait for instance to be fully terminated
      ansible.builtin.pause:
        seconds: 30
      when: ansible_verbosity >= 1

    - name: Delete security group
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        region: "{{ aws_region }}"
        state: absent
      retries: 5
      delay: 10
      register: sg_result
      until: sg_result is not failed

    - name: Get route table info for deletion
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: route_table_info

    - name: Delete route table
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ item.route_table_id }}"
        region: "{{ aws_region }}"
        lookup: id
        state: absent
      loop: "{{ route_table_info.route_tables | default([]) }}"
      when:
        - not item.associations[0].main | default(false)
        - item.route_table_id is defined
      failed_when: false

    - name: Delete subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        cidr: "{{ vpc_cidr }}"
        az: "{{ availability_zone }}"
        region: "{{ aws_region }}"
        state: absent
      retries: 3
      delay: 10
      failed_when: false

    - name: Delete internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
      retries: 3
      delay: 10
      failed_when: false

    - name: Show cleanup result
      ansible.builtin.debug:
        msg: |
          Cleanup completed for {{ instance_name }}
          Environment: {{ resource_tags.Environment }}
          All resources destroyed in {{ aws_region }}
