---
- name: Update packages on EC2 instance
  hosts: ec2_servers
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Show what we're updating
      ansible.builtin.debug:
        msg: "Updating packages on {{ inventory_hostname }}"

    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install automatic security updates
      ansible.builtin.yum:
        name: yum-cron
        state: present

    - name: Start automatic security updates
      ansible.builtin.service:
        name: yum-cron
        enabled: yes
        state: started

    - name: Show completion message
      ansible.builtin.debug:
        msg: |
          Package update completed!
          All packages are now up to date
          Automatic security updates are enabled