---
# Password Policy Security Tasks
# Implements password complexity and aging policies

- name: Configure password security settings
  ios_config:
    lines:
      - security passwords min-length {{ min_password_length }}
      - security authentication failure rate {{ auth_failure_rate }} log
      
- name: Configure password aging
  ios_config:
    lines:
      - username {{ item.username }} password-policy {{ password_policy_name }}
  loop: "{{ local_users }}"
  when: local_users is defined and password_policy_name is defined
  
- name: Configure login block settings
  ios_config:
    lines:
      - login block-for {{ login_block_time }} attempts {{ login_attempts }} within {{ login_time_window }}
      - login quiet-mode access-class {{ login_quiet_acl }}
  when: login_block_time is defined and login_attempts is defined
  
- name: Configure login delay
  ios_config:
    lines:
      - login delay {{ login_delay }}
  when: login_delay is defined
  
- name: Configure login on-failure log
  ios_config:
    lines:
      - login on-failure log
      - login on-success log
      
- name: Configure password encryption
  ios_config:
    lines:
      - service password-encryption
      
- name: Configure password recovery
  ios_config:
    lines:
      - no service password-recovery
  when: disable_password_recovery | default(false)